# -*- coding: utf-8 -*-
"""main.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QnhV58iEUoZUnIroV-SFVgyOLwm1KlZs
"""

import joblib
import pandas as pd
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel

# 1. Inicializar la aplicación
app = FastAPI(
    title="NBA Playoff Predictor API",
    description="API para predecir si un equipo llegará a playoffs basado en estadísticas.",
    version="1.0"
)

# 2. Cargar el modelo al iniciar
# Asegúrate de que el archivo .joblib esté en la misma carpeta
try:
    model = joblib.load("modelo_nba.joblib")
    print("Modelo cargado exitosamente.")
except FileNotFoundError:
    print("Error: No se encontró el archivo 'modelo_nba.joblib'.")

# 3. Definir la estructura de los datos de entrada (Data Schema)
# Esto valida que el usuario envíe números y no texto
class TeamStats(BaseModel):
    win_pct: float      # Porcentaje de victorias (ej. 0.55)
    points_pg: float    # Puntos por juego (ej. 115.5)
    opp_points_pg: float # Puntos recibidos por juego (ej. 110.2)
    conf_rank: int      # Ranking en la conferencia (ej. 8)

    class Config:
        schema_extra = {
            "example": {
                "win_pct": 0.55,
                "points_pg": 115.0,
                "opp_points_pg": 112.5,
                "conf_rank": 7
            }
        }

# 4. Crear el Endpoint de Predicción
@app.post("/predict")
def predict_playoffs(stats: TeamStats):
    try:
        # Convertir los datos recibidos a un DataFrame
        # IMPORTANTE: Los nombres de las columnas deben coincidir con los usados en el entrenamiento
        features = pd.DataFrame([[
            stats.win_pct,
            stats.points_pg,
            stats.opp_points_pg,
            stats.conf_rank
        ]], columns=['WinPCT', 'PointsPG', 'OppPointsPG', 'ConfRank'])

        # Realizar la predicción
        prediction = model.predict(features)[0]                 # 0 o 1
        probability = model.predict_proba(features)[0][1]       # Probabilidad de ser 1

        # Crear respuesta
        result = "CALIFICA" if prediction == 1 else "NO CALIFICA"

        return {
            "prediction": result,
            "probability_score": round(probability, 4),
            "probability_percent": f"{round(probability * 100, 2)}%",
            "input_data": stats
        }

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

# 5. Endpoint de prueba (Health Check)
@app.get("/")
def home():
    return {"message": "La API de NBA está funcionando correctamente."}