# -*- coding: utf-8 -*-
"""main.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QnhV58iEUoZUnIroV-SFVgyOLwm1KlZs
"""

import joblib
import pandas as pd
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel

# 1. Inicializar App
app = FastAPI(
    title="NBA Playoff Predictor",
    description="Predice si un equipo clasifica a playoffs basándose en desempeño (No Ranking).",
    version="2.0"
)

# 2. Cargar Modelo
try:
    model = joblib.load("modelo_nba.joblib")
    print("Modelo cargado correctamente.")
except:
    print("ADVERTENCIA: No se encontró 'modelo_nba.joblib'.")

# 3. Definir Schema de Datos (ACTUALIZADO)
class TeamStats(BaseModel):
    win_pct: float       # Ej: 0.55
    points_pg: float     # Ej: 114.5
    opp_points_pg: float # Ej: 112.0
    diff_points_pg: float # Ej: 2.5 (Diferencial)

    class Config:
        schema_extra = {
            "example": {
                "win_pct": 0.55,
                "points_pg": 115.0,
                "opp_points_pg": 112.0,
                "diff_points_pg": 3.0
            }
        }

# 4. Endpoint de Predicción
@app.post("/predict")
def predict(stats: TeamStats):
    try:
        # Convertir input a DataFrame con los nombres EXACTOS del entrenamiento
        features = pd.DataFrame([[
            stats.win_pct,
            stats.points_pg,
            stats.opp_points_pg,
            stats.diff_points_pg
        ]], columns=['WinPCT', 'PointsPG', 'OppPointsPG', 'DiffPointsPG'])

        # Predecir
        prediction = model.predict(features)[0]
        prob = model.predict_proba(features)[0][1]

        result_text = "CALIFICA" if prediction == 1 else "NO CALIFICA"

        return {
            "prediction": result_text,
            "probability": f"{round(prob * 100, 2)}%",
            "details": {
                "win_pct": stats.win_pct,
                "diff_points": stats.diff_points_pg
            }
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.get("/")
def home():
    return {"status": "API Online v2.0"}